services:
  database:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: Dev-Dockerfile
    env_file:
      - .env
    volumes:
      - .:/ror
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - database
volumes:
  db_data:
  gem_cache: